#pragma once

#include <stdint.h>
#include <stdbool.h>
#include <windows.h>

#define LOG_FILE "log.txt"
#define APP_VERSION "v1.12"

#define ID_MAIN_ADD 60
#define ID_MAIN_EDIT 61
#define ID_MAIN_DELETE 62
#define ID_MAIN_SETTINGS 63
#define ID_MAIN_QUIT 64
#define ID_MAIN_FINDTEXT 65
#define ID_MAIN_FIND 66
#define ID_MAIN_LISTBOX 67

#define ID_EDIT_TITLE_LABEL 10
#define ID_EDIT_TITLE 11
#define ID_EDIT_TITLE_COUNT 12
#define ID_EDIT_ID_LABEL 13
#define ID_EDIT_ID 14
#define ID_EDIT_ID_COUNT 15
#define ID_EDIT_PW_LABEL 16
#define ID_EDIT_PW 17
#define ID_EDIT_PW_COUNT 18
#define ID_EDIT_MISC_LABEL 19
#define ID_EDIT_MISC 20
#define ID_EDIT_MISC_COUNT 21
#define ID_EDIT_COPY_PASSWORD 22

#define ID_OK 25
#define ID_CANCEL 26
#define ID_GENERATE 27

#define ID_SETTINGS_PW_LABEL 30
#define ID_SETTINGS_PW_LENGTH 31
#define ID_SETTINGS_SPECIAL_LABEL 32
#define ID_SETTINGS_SPECIAL_LENGTH 33
#define ID_SETTINGS_NUMERIC_LABEL 34
#define ID_SETTINGS_NUMERIC_LENGTH 35
#define ID_SETTINGS_UPPERCASE_LABEL 36
#define ID_SETTINGS_UPPERCASE_LENGTH 37
#define ID_SETTINGS_KEYGEN_LABEL 38
#define ID_SETTINGS_KEYGEN_LENGTH 39
#define ID_SETTINGS_SET_PASSWORD 40
#define ID_SETTINGS_VERSION 41
#define ID_SETTINGS_EXPORT_DB 42

#define ID_PASSWORD_LABEL1 50
#define ID_PASSWORD_PASSWORD1 51
#define ID_PASSWORD_LABEL2 52
#define ID_PASSWORD_PASSWORD2 53
#define ID_PASSWORD_MESSAGE 54
#define ID_PASSWORD_WARNING 55

#define ID_TIMER1 1
#define ID_TIMER2 2
#define ID_TIMER3 3

void enableControls(void);
void disableControls(void);
void centerWindow(HWND);
void fillListbox(void);
void updateListbox(void);
void deleteEntry(void);
bool isNumeric(char *buf);
void fillDropdown(HWND, int, int);
void outs(char *);
void shutDown(HWND);
void sendTab(void);

LRESULT CALLBACK mainWndProc(HWND, UINT, WPARAM, LPARAM);
LRESULT CALLBACK addWndProc(HWND, UINT, WPARAM, LPARAM);
LRESULT CALLBACK editWndProc(HWND, UINT, WPARAM, LPARAM);
LRESULT CALLBACK settingsWndProc(HWND, UINT, WPARAM, LPARAM);
LRESULT CALLBACK setPasswordWndProc(HWND, UINT, WPARAM, LPARAM);
LRESULT CALLBACK getPasswordWndProc(HWND, UINT, WPARAM, LPARAM);
LRESULT CALLBACK customFindProc(HWND, UINT, WPARAM, LPARAM);
LRESULT CALLBACK customListboxProc(HWND, UINT, WPARAM, LPARAM);
LRESULT CALLBACK customAddProc(HWND, UINT, WPARAM, LPARAM);
LRESULT CALLBACK customAddMiscProc(HWND, UINT, WPARAM, LPARAM);
LRESULT CALLBACK customEditProc(HWND, UINT, WPARAM, LPARAM);
LRESULT CALLBACK customEditMiscProc(HWND, UINT, WPARAM, LPARAM);
LRESULT CALLBACK customSetPasswordProc(HWND, UINT, WPARAM, LPARAM);
LRESULT CALLBACK customGetPasswordProc(HWND, UINT, WPARAM, LPARAM);
